/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a3d2f582-6754-414b-9175-7e123bb9afba",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Rjsr2rHxb",
    "aws_user_pools_web_client_id": "f6snu0gq4cl8u5v3p1kkgis1",
    "oauth": {}
};


export default awsmobile;
